### ISSUE TITLE
Could not onlyoffice document editor.

### ISSUE THREAD

**Issue by mtcoliveira** [humhub-contrib/onlydocuments#1]
I have done the installation and configuration of the DocumentServer.
The system and humhub can connect to the DocumentServer, but when I try to edit or online view some document the following error appears:

Could not onlyoffice document editor.

**Comment by trofim24** [comment]
You installed the OnlyOffice DocumentServer and entered its link in the configuration?
Link to https://doc.onlyoffice.com works for you?

**Comment by mtcoliveira** [comment]
Yes i did. If i enter in my server address i can view the "Document Server is running"

**Comment by trofim24** [comment]
> [Could not onlyoffice document editor.](https://github.com/humhub/humhub-modules-onlydocuments/blob/master/resources/humhub.onlydocuments.js#L80)

This error occurs if there is no DocsAPI. 
Do you have errors in the browser console and is the server onlyoffice accessible from the outside?

**Comment by mtcoliveira** [comment]
This is my configuration under the module:
![image](https://user-images.githubusercontent.com/25369411/27491008-f9b1f71e-5816-11e7-8abd-26b918aae191.png)


This is the error when i try to edit a document:
![image](https://user-images.githubusercontent.com/25369411/27491033-1381db1e-5817-11e7-9dac-a29730af2e2e.png)

Here is a screenshot of welcome page of DocumentServer:
![image](https://user-images.githubusercontent.com/25369411/27491054-2e1a6ae0-5817-11e7-8cdc-bf0a5b2a97a3.png)


This address is not accessible from outside.

**Comment by trofim24** [comment]
Is the api file available to you?
http://intranet.terrenaagro.com.br:8080/web-apps/apps/api/documents/api.js

**Comment by mtcoliveira** [comment]
Yes

![image](https://user-images.githubusercontent.com/25369411/27550267-73ccde6e-5a75-11e7-8aa5-ae6dd72e5b12.png)

**Comment by trofim24** [comment]
Can you export the Network Timeline as HAR File when you try to edit a document?

**Comment by mtcoliveira** [comment]
Here is the HAR file
[intranet.terrenaagro.com.br.har.zip](https://github.com/humhub/humhub-modules-onlydocuments/files/1103858/intranet.terrenaagro.com.br.har.zip)

**Comment by caumons** [comment]
I had exactly the same error and I solved it using the server IP (and port) instead of localhost as the Hostname. The web browser requests the api file as suggested by @trofim24 and, of course, if you wrote "localhost" it won't found the file. Would be nice to expand docs on this.

**Comment by solracsf** [comment]
Having the same issue here with
`DocumentServer successfully connected! - Installed version: 5.0.7.38`

I've tried the Private IP, Public IP.

The API is available at
`http://MY_IP:4709/web-apps/apps/api/documents/api.js`

but i have this message
`Could not onlyoffice document editor`

**Comment by solracsf** [comment]
Ok so in my case the HumHub is accessed trough `HTTPS` so `DocumentServer URL` **must be** `HTTPS` too otherwise the **API is blocked** _(mixed content blocked by the browser)_.
