### ISSUE TITLE
NOn-admin users cant edit documents-humhub

### ISSUE THREAD

**Issue by Derango5** [humhub-contrib/onlydocuments#13]
i installed onlyoffice-document server for humhub and it work for admin user
![doc](https://user-images.githubusercontent.com/36234637/36366833-91cbfad2-1558-11e8-8e00-bdbf608f83b5.JPG)

but for a non-admin user the edit option is not applicable, i dont know why

![nonad](https://user-images.githubusercontent.com/36234637/36366896-e589a5d4-1558-11e8-8e6c-3920d4592c05.JPG)

any work around on this? 

thank you.

**Comment by bonnyTR** [comment]
Hi!
How do you've resolve this behaivour?
I've installed HumHub yesterday and i'm incurring in the same problem. 
I've notice that only the owner of the file can edit it and the administrator obviusly can done all.
My target is to use the co-editing features of OnlyOffice.
Any Suggest?
Thanks!!

**Comment by plmorpheus** [comment]
Up!
