### ISSUE TITLE
DocumentServer not accessible.

### ISSUE THREAD

**Issue by irfan-yusanif** [humhub-contrib/onlydocuments#15]
1.  I hosted humhub code on `abc.com`. 

2.  For OnlyOffice - DocumentServer Integration, I downloaded only office code from [here](https://github.com/ONLYOFFICE/DocumentServer/releases) and uploaded code in root directory of `abc.com`.

3. When I hit the url `https://abc.com/web-apps/apps/api/documents/api.js`, it shows the js file code, means the only office document server is successfully deployed?

4. 

![image](https://user-images.githubusercontent.com/5346797/39666341-a5187f54-50bb-11e8-99d2-5b50da348035.png)

I know I'm doing something wrong, but couldn't figure out what is wrong. website is on https.

**Comment by bambus1980** [comment]
you need first to install Onlyoffice server and confirm it working. Before you can connect ti it from Humhub.
Sorry, but I didn't test it yet.

**Comment by irfan-yusanif** [comment]
Hi, how to install and where to install?
By installing the Onlyoffice server, you mean I have to copy the onlyoffice git source code to my website. Right? 

Sorry I have read the documentation but couldn't find where to get document server and where to install

**Comment by solracsf** [comment]
https://helpcenter.onlyoffice.com/server/linux/document/index.aspx
