### ISSUE TITLE
Document Server is not accessible, even when the server is running

### ISSUE THREAD

**Issue by carlosdmz** [humhub-contrib/onlydocuments#17]
Hey,

I've read all of other issues about this particular problem, but none of them seemed to work. I had set up a document server and tried to integrate it with humhub through this module. However, it's still throwing this "Document Server is not accessible" error.

The document server is running, alongside with all the dependencies on Debian 8 Jessie and Nginx configured as shown in the docs. On a side note, Humhub is running in https protocol, while the document server is running in http protocol.

Is the problem related regarding in my document server running on HTTP while humhub instance is running in HTTPS? If it's not the case, what it could be?

Thanks in advance.

![screenshot-2018-6-15 3 administracao](https://user-images.githubusercontent.com/10291163/41481749-85422be0-70a9-11e8-8f06-0d314915bbee.png)

![screenshot-2018-6-15 onlyoffice](https://user-images.githubusercontent.com/10291163/41481750-857b3584-70a9-11e8-9817-7ab40d869fee.png)

**Comment by Ace2213** [comment]
@carlosdamazio How did you resolve this?

**Comment by carlosdmz** [comment]
@Ace2213 Well, it's been a long time though...

But I managed to make the document server HTTPS to avoid mixed content, which prevented the connection to be established.
