### ISSUE TITLE
Not the correct file when download

### ISSUE THREAD

**Issue by karimbernardet** [humhub-contrib/onlydocuments#18]
Hi

We have deployed Humhub + OnlyOffice. We have noticed that when we modify a file using OnlyOffice, the file uploaded thru Humhub is not the modified one but the original file uploaded at the beginning. But if we edit the file (clicking on Edit), we have the correct modified file. 
Is it a normal behavior ?
(humhub version 1.2.7, onlyoffice module 1.0.2)
Thanks for any tip. 

Karim

**Comment by luke-** [comment]
It takes some time until onlyoffice uploads the modified files to HumHub.
