### ISSUE TITLE
Humhub callback unexceptionally using http instead of https.

### ISSUE THREAD

**Issue by boubouX** [humhub-contrib/onlydocuments#19]
I'm using both Humhub and Onlyoffice document server behind nginx https reverse proxy.  I have set the base URL under settings to use https://...  Both work well independently, however the callback url given from humhub to the Onlyoffice doc server is using http: and fails because of the redirect error.

**Comment by luke-** [comment]
You can add following to your HumHub configuration file

`$_SERVER['HTTPS'] = 'on';`

Or, alternatively you can add the frontend proxy as trusted host:

return [
    'components' => [
        'request' => [
            'trustedHosts' => ['IP OF FRONTEND PROXY']
        ]
    ]
];
