### ISSUE TITLE
Message : DocumentServer not accessible.

### ISSUE THREAD

**Issue by ghost** [humhub-contrib/onlydocuments#6]
Hello, 

i m using  HUMHUB  1.2.2

and i have my onlyoffice serveur, working at the adresse : https://oo.Domaine.com

but i have this error : 

![image](https://user-images.githubusercontent.com/301074/31483843-562f450a-af2e-11e7-990a-25b5bd5d3fcf.png)

do u know how fix this please, to access onlyOffice with humhub  ?

thanks

**Comment by trofim24** [comment]
Hello, @ychoucha 
Is your server available?

**Comment by ghost** [comment]
Hello yes it's works,

i using it now

**Comment by ghost** [comment]
When i create a document in humhub i have this error : 

![image](https://user-images.githubusercontent.com/301074/31496951-a4440bf2-af5d-11e7-8726-cd0cdee2a5e9.png)

**Comment by trofim24** [comment]
Is opening a document outside the humhub on the DocumentServer itself?

**Comment by ghost** [comment]
Hello, 
thanks u right, 

this is a onlyOffice issue, when i try to create a document on it ihave this error : 

![image](https://user-images.githubusercontent.com/301074/31532553-3f9c9d90-afee-11e7-8c01-b872cae2206a.png)

i have to see with onlyoffice support

thanks
