### ISSUE TITLE
DocumentServer not accesible

### ISSUE THREAD

**Issue by spardo83** [humhub-contrib/onlydocuments#9]
I have a running instance of onlyoffice, but when i try to add it to my humhub modules config i cant get it work.
![captura](https://user-images.githubusercontent.com/22061879/33554289-db7494d8-d8da-11e7-81bd-ca8e2878e8bd.PNG)
![onlyofficeerror](https://user-images.githubusercontent.com/22061879/33554291-dc0dba50-d8da-11e7-9e36-fef849dfa58e.PNG)

Any missing config? or version problems?

**Comment by ShockwaveNN** [comment]
@sebasunlam Seems you running pretty old version of DocumentServer, like v.3

**Comment by spardo83** [comment]
Its any free version of DocumentServer v4?

**Comment by ShockwaveNN** [comment]
@sebasunlam Current stable is 5.0.5.26 and it has free version https://github.com/ONLYOFFICE/DocumentServer

**Comment by spardo83** [comment]
Have any link? i found this
http://onlyoffice.org/sources
But i never use docker and it´s version 4.3

**Comment by ShockwaveNN** [comment]
@sebasunlam https://github.com/ONLYOFFICE/DocumentServer/releases

**Comment by spardo83** [comment]
Thanks!!! closing this!
